---
title: "Sound_hab_spl_correlations"
author: "Becca Van Hoeck"
date: "3/29/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load libraries and data
```{r}
library(ggplot2)
library(GGally)
library(dplyr)
library(tidyr)

ecometrics = read.csv("data/clean_data/ecometrics.csv")

```

## Explore correlations:

```{r}
sound_hab = ecometrics %>%
  select(site, habitat, seagrass_comb, oyster, saltmarsh, richness, shannonD,
         avg_shoot_density, avg_blade_length,
        avg_spl_low, avg_spl_high)

ggpairs(sound_hab[,3:11])

sound_com = ecometrics %>%
  select(site, habitat, depth_m_avg, temp_avg, sal_avg, total_abund_sum, comm_shannonD_sum, 
         piscivore, avg_spl_low, avg_spl_high)

#sound_com$log_abund = log10(sound_com$total_abund_sum)
#plot(sound_com$total_abund_sum)

ggpairs(sound_com[,3:10])

# only piscivore was interesting
# sound_trophic = ecometrics %>%
#   select(site, habitat, carnivore, piscivore, planktivore, 
#          avg_spl_low, avg_spl_high)
# 
# ggpairs(sound_trophic[,3:7])


```

## Things to do

repeat correlations with final dataframes

```{r}
benthic_cor = cor(site_means[,-c(1:2)])
round(benthic_cor,3)

benthic_comb_cor = cor(site_means_comb[,-c(1:2)])
round(benthic_comb_cor,3)

```

## Plots

```{r}


# add habitat label and filter to only seagrass

#Benthic metrics
ggplot(aes(x = richness_comb, y = avg_spl_low, color = habitat), data = ecometrics)+
  geom_point()

ggplot(aes(x = shannonD , y = avg_spl_low, color = habitat), data = ecometrics)+
  geom_point()

ggplot(aes(x = totalcover, y = avg_spl_low, color = habitat), data = ecometrics)+ theme_bw()+
  geom_point(size = 3)+
  geom_smooth(method = "lm", se = FALSE)+
  scale_color_discrete(name = "Habitat type")+
  ylab("Average sound pressure level (db re 1 uPa")+ 
  xlab("Average percent cover")+
  theme(axis.text = element_text(size = 16), 
        axis.title = element_text(size = 18), 
        legend.title = element_text(size = 18), 
        legend.text = element_text(size = 16))

#Habitat Metrics
ggplot(aes(x = seagrass_comb, y = avg_spl_low, color = habitat), data = ecometrics)+
  geom_point()

ggplot(aes(x = saltmarsh, y = avg_spl_low, color = habitat), data = ecometrics)+
  geom_point()

ggplot(aes(x = saltmarsh, y = avg_spl_high, color = habitat), data = ecometrics)+
  geom_point()

ggplot(aes(x = oyster, y = avg_spl_high, color = habitat), data = ecometrics)+
  geom_point()

ggplot(aes(x = oyster, y = avg_spl_low, color = habitat), data = ecometrics)+
  geom_point()

# Community metrics
ggplot(aes(x = total_abund_sum, y = avg_spl_low, color = habitat), data = ecometrics)+
  geom_point()

ggplot(aes(x = comm_shannonD_sum, y = avg_spl_low, color = habitat), data = ecometrics)+
  geom_point()

ggplot(aes(x = comm_richness_sum, y = avg_spl_low, color = habitat), data = ecometrics)+
  geom_point()

ggplot(aes(x = X1_Depth_m, y = avg_spl_low, color = habitat), data = ecometrics)+
  geom_point()

#ecometrics[is.na(ecometrics)] = 0
#sound_eco_cor = cor(ecometrics[,c(6:24,27:62)], use = "pairwise.complete.obs")

```
